# version: '3'
services:
  fastapi_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Expose port 8000 for internal communication
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Expose port 80 to the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount Nginx config
    depends_on:
      - fastapi_app
    restart: always

